# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCloudMusicSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCloudMusicSwift
  
  # 提示框架
  # https://github.com/jdg/MBProgressHUD
  pod 'MBProgressHUD', '~> 1.1.0'

  target 'MyCloudMusicSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyCloudMusicSwiftUITests' do
    # Pods for testing
  end

end
